### ISSUE TITLE
Proxy kwarg doesn't seem to exist

### ISSUE THREAD

**Issue by tg295** [maxmind/GeoIP2-python#109]
Running:

`import geoip2.webservice
geo_client = geoip2.webservice.Client(
    account_id=xxxx,
    license_key='XXX',
    locales=['en'],
    proxy=os.environ['PROXY_VAR'])`

returns:

`TypeError: __init__() got an unexpected keyword argument 'proxy'`

Despite the fact it's listed as a param here: https://github.com/maxmind/GeoIP2-python/blob/main/geoip2/webservice.py#L410

I also notice the param is non-existent in the documentation: https://geoip2.readthedocs.io/en/latest/#geoip2.webservice.Client

Is there any particular reason why?

**Comment by oschwald** [comment]
That functionality was added after the latest release.

**Comment by oschwald** [comment]
I just release [4.2.0](https://pypi.org/project/geoip2/4.2.0/) with this.

**Comment by tg295** [comment]
thank you!
