### ISSUE TITLE
Get county from city database

### ISSUE THREAD

**Issue by nkmaurya-dev** [maxmind/GeoIP2-python#112]
How can we get county from the city database reader? We can get country, city, state and other entities but not the county.
Example:
```
ip = '74.221.14.63'
result = reader.city(ip)
state = result.subdivisions.most_specific.name
city = result.city.name
print(state) # Tennessee
print(city) # Millington
```

The county would be **Shelby** for the above entities
County finder: http://www.statsamerica.org/CityCountyFinder

**Comment by oschwald** [comment]
MaxMind databases do not provide county-level data in the US.
