### ISSUE TITLE
how to get queries_remaining without doing an IP lookup

### ISSUE THREAD

**Issue by skunkwerk** [maxmind/GeoIP2-python#14]
I'm currently doing this:

from geoip2 import webservice
client = webservice.Client(12345, '************')
city = client.city()
city.maxmind.queries_remaining

But the problem is every time I issue that query, my number of queries remaining goes down by 1, even though I don't actually want to do an IP lookup - I just want to see my account status.

Is there any way to get the queries_remaining without doing an IP lookup?

thanks

**Comment by SightStudio** [comment]
I have the same issue in 2020. getting queries_remaining without IP lookup is still not available?

**Comment by SightStudio** [comment]
I have the same issue in 2020. Getting queries_remaining without IP lookup is still not available?

And I wonder if minfraud is the same.

@oschwald

**Comment by oschwald** [comment]
MaxMind does not provide a separate endpoint for looking up queries remaining at this time.
