### ISSUE TITLE
Incompatiblity with recent redis-py releases

### ISSUE THREAD

**Issue by takecare** [maxmind/GeoIP2-python#142]
Recent redis-py releases depend on `async-timeout` >= 4.0.2, which clashes with geoip2's dependency set on `aiohttp`, which depends on `async-timeout` <4.0.0. Are there plans to tackle this?

**Comment by oschwald** [comment]
It appears that the latest release of `aiohttp` [depends on `async-timeout` 4.x.x](https://github.com/aio-libs/aiohttp/blob/33953f110e97eecc707e1402daa8d543f38a189b/setup.cfg#L54). Maybe you need to upgrade `aiohttp`.
