### ISSUE TITLE
Release new version to resolve urllib3 constraint issue

### ISSUE THREAD

**Issue by UsamaSadiq** [maxmind/GeoIP2-python#144]
## Description
- `urllib3` latest version `urllib3==2.0.2` is now available on PyPI and the constraint for the package has also been loosened up in the PR https://github.com/maxmind/GeoIP2-python/pull/143
-  Current version of `geoip2` conflicts with the `requests`, `py2neo` and other packages when installing latest versions of each package because of the `urllib3` constraint.
```
There are incompatible versions in the resolved dependencies:
  urllib3==2.0.2 (from -r requirements/edx/paver.txt (line 51))
  urllib3<2.0.0,>=1.25.2 (from geoip2==4.6.0->-r requirements/edx/base.in (line 109))
  urllib3 (from py2neo==2021.2.3->-r requirements/edx/base.in (line 143))
  urllib3<3,>=1.21.1 (from requests==2.30.0->-r requirements/edx/paver.txt (line 40))
```
- Releasing a new version will resolve the blocker when installing packages together.

**Comment by oschwald** [comment]
A new version was released.
