### ISSUE TITLE
update conda-forge packages

### ISSUE THREAD

**Issue by loriab** [maxmind/GeoIP2-python#153]
Hi, I'm associated with a project that uses your geoip2 package, and we noticed that it's out of date on conda-forge (v4.0.2 ; https://github.com/conda-forge/geoip2-feedstock) as opposed to pypi (v4.7.0 ; https://pypi.org/project/geoip2/). The conda package is also omitting to declare its runtime dependencies, of which maxminddb is also rather out of date. They don't appear to have been updated since the original packaging nearly 3 years ago.

From #74, it sounds like you here upstream don't have much association with the conda package and probably don't know the c-f maintainer, @rverma129 . Nonetheless, I thought I'd mention the situation to you and make sure there weren't any objections to updating the conda packages.

I've already put up update PRs for maxminddb and geoip2 (latter failing for want of former) here https://github.com/conda-forge/maxminddb-feedstock/pull/5 and https://github.com/conda-forge/geoip2-feedstock/pull/7 . I'll probably merge them in a month or so if there's no action or objections. I'd merge them sooner if you explicitly approve. Thanks!

@bennybp

**Comment by oschwald** [comment]
That is correct; we don't have an association with the packages. I took a look at the PRs and they seemed reasonable to me. Thanks!

**Comment by loriab** [comment]
Both updated now, thanks!
