### ISSUE TITLE
error when running GeoIP2 in GeoDjango project

### ISSUE THREAD

**Issue by iamlauriano** [maxmind/GeoIP2-python#167]
I'm testing geoIP2 in conjunction with GeoDjango 
https://docs.djangoproject.com/en/5.0/ref/contrib/gis/geoip2/

I installed GeoIP2, according to the documentation
https://pypi.org/project/geoip2/

However, it presents this error when calling the service
>>> import geoip2.database
>>> g = GeoIP2()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/lauriano/lauriano88/bamburralrural/venv/lib/python3.10/site-packages/django/contrib/gis/geoip2/base.py", line 78, in __init__
    raise GeoIP2Exception(
django.contrib.gis.geoip2.base.GeoIP2Exception: GeoIP path must be provided via parameter or the GEOIP_PATH setting.

**Comment by oschwald** [comment]
I think this would be better directed at the Django project. It sounds like `GEOIP_PATH` has to be set. The error is not from the code in this library.
