### ISSUE TITLE
Query mmdb file to get ips examples 

### ISSUE THREAD

**Issue by YardenMarkus** [maxmind/GeoIP2-python#168]
I'm looking for ipv6 examples to run some tests and I can't find a way to query mmdb file to get a few IP addresses. I can only query it with a specific IP. For example, I need some ipv6 with and without ISP, and a few ips from different countries. Is there a way to do this?

**Comment by oschwald** [comment]
The data is only indexed by IP. You could [iterate over the database](https://github.com/maxmind/MaxMind-DB-Reader-python#:~:text=You%20may%20also%20iterate%20over%20the%20whole%20database.%20The%20Reader%20class%20implements%20the%20__iter__%20method%20that%20returns%20an%20iterator.%20This%20iterator%20yields%20a%20tuple%20containing%20the%20network%20and%20the%20record.) until you find a record that meets your needs or you could similarly grep one of the CSV databases for such data.

That said, if you are writing unit or integration tests, I would suggest using the test databases from [this repo](https://github.com/maxmind/MaxMind-DB).
