### ISSUE TITLE
what's wrong with response.country.names?

### ISSUE THREAD

**Issue by lenovo-me** [maxmind/GeoIP2-python#21]
[Imgur](http://i.imgur.com/bGFhOvp.png)
why it‘s not print United States?

python 2.7.9
cffi (0.8.6)
cryptography (0.7.1)
dnslib (0.9.3)
geoip2 (2.1.0)
gevent (1.0.1)
gfwlist2pac (1.1.2)
greenlet (0.4.5)
maxminddb (1.1.1)
pip (1.5.6)
pycparser (2.10)
pycrypto (2.6.1)
pygeoip (0.3.2)
pyOpenSSL (0.13.1)
pywin32 (219)
setuptools (11.3.1)
six (1.9.0)

**Comment by autarch** [comment]
The output includes `u'en': 'United States'`

The `names` method returns a dictionary containing names for various locales, keyed on the locale code. I think if you write `response.country.names['en']` you'll get what you want.

As an aside, in the future, pasting the actual code and its output into the ticket is greatly preferred over a screenshot.

**Comment by oschwald** [comment]
Also, `response.country.name` (no "s") will return the English name (assuming you didn't change the default locales).

**Comment by lenovo-me** [comment]
OK,it's my fault.Thank you very much.
