### ISSUE TITLE
Context manager support

### ISSUE THREAD

**Issue by hongquan** [maxmind/GeoIP2-python#28]
It would be more Pythonic if you guys support Python's context manager for `geoip2.database.Reader`, so that we can call:

```python
with geoip2.database.Reader('GeoLite2-City.mmdb') as reader:
    r = reader.city(ip_addr)
    data = {
        'country_code': r.country.iso_code,
        'country_name': r.country.name
    }
```

and `reader.close()` is called automatically when exiting `with`.

**Comment by oschwald** [comment]
I agree. Any chance you could make a PR for this?
