### ISSUE TITLE
No module named database

### ISSUE THREAD

**Issue by zhangzfmail** [maxmind/GeoIP2-python#33]
I create a python script with geoip2, but system report error saying "No module named database"

Traceback (most recent call last):
  File "geoip2.py", line 2, in <module>
    import geoip2
  File "/home/ubuntu/google/geoip2.py", line 3, in <module>
    import geoip2.database
ImportError: No module named database

My code:
#!/usr/bin/env python
import geoip2.database
reader = geoip2.database.Reader('/usr/share/GeoIP2/GeoLite2-City.mmdb')
response = reader.city('78.31.107.133')
print response.country.iso_code

**Comment by oschwald** [comment]
Try naming your script something other than `geoip2.py`.

**Comment by zhangzfmail** [comment]
I tried, changing name does not work

**Comment by oschwald** [comment]
Be sure to remove any compiled byte-code (e.g., `geoip2.pyc`), e.g.:

```sh
$ cat geoip2.py
#!/usr/bin/env python
import geoip2.database
reader = geoip2.database.Reader('/usr/share/GeoIP/GeoLite2-City.mmdb')
response = reader.city('78.31.107.133')
print response.country.iso_code

$ python geoip2.py
Traceback (most recent call last):
  File "geoip2.py", line 2, in <module>
    import geoip2.database
  File "/tmp/geoip2.py", line 2, in <module>
    import geoip2.database
ImportError: No module named database

$ mv geoip2.py some-other-name.py

$ python some-other-name.py 
Traceback (most recent call last):
  File "some-other-name.py", line 2, in <module>
    import geoip2.database
  File "/tmp/geoip2.py", line 2, in <module>
ImportError: No module named database

$ rm geoip2.pyc 

$ python some-other-name.py 
GB
```

**Comment by zhangzfmail** [comment]
Thank you, it works now
