### ISSUE TITLE
Nonexistent database raises FileNotFoundError

### ISSUE THREAD

**Issue by PyDeq** [maxmind/GeoIP2-python#42]
Can you please take a look at this:

# Reproducer

1. make sure that `nonexistent.mmdb` does not exist
2. call `geoip2.database.Reader('nonexistent.mmdb')`

# Actual result

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib/python3.5/site-packages/geoip2/database.py", line 82, in __init__
    self._db_reader = maxminddb.open_database(filename, mode)
  File "/tmp/venv/lib/python3.5/site-packages/maxminddb/__init__.py", line 32, in open_database
    return maxminddb.extension.Reader(database)
FileNotFoundError: No such file or directory: 'nonexistent.mmdb'
```

# Expected result

A `ValueError` or a change in [the documentation](http://geoip2.readthedocs.io/en/latest/#database-reader-exceptions).

# Versions

geoip2 2.4.2
maxminddb 1.2.3
libmaxminddb-dev 1.0.4-2.1
libmaxminddb0 1.0.4-2.1
Python 3.5.2
Ubuntu 16.04.1

**Comment by oschwald** [comment]
Thanks. The documentation should probably be updated in this case as `FileNotFoundError` seems like the appropriate exception.
