### ISSUE TITLE
database reader not working on python3

### ISSUE THREAD

**Issue by gjcarneiro** [maxmind/GeoIP2-python#5]
I got this stack trace from python3

```
Traceback (most recent call last):
  File "report.py", line 40, in <module>
    parse_file(fname)
  File "report.py", line 31, in parse_file
    country = geoip.country(ipaddr)
  File "/usr/local/lib/python3.3/dist-packages/geoip2/database.py", line 60, in country
    return self._model_for(geoip2.models.Country, ip_address)
AttributeError: 'module' object has no attribute 'models'
```

The solution I found was to open `/usr/local/lib/python3.3/dist-packages/geoip2/database.py`  and add  the line `import geoip2.models`.

I assume this is a python3 specific problem, but I didn't check if it works on python2.

**Comment by venkateshmora23** [comment]
Hello, I am not able to use geoip2 in spark or redshift. I installed geoip2 on a spark cluster on all the nodes when I run the job, it picks up the library geoip2 but throws -- AttributeError: 'module' object has no attribute 'database'.

**Comment by daniilmaltsev** [comment]
@venkateshmora23, as a workaround, try importing the database directly, i.e:
import geoip2.database
