### ISSUE TITLE
IP range not found by ASN reader

### ISSUE THREAD

**Issue by crotsos** [maxmind/GeoIP2-python#52]
I am using the following python code:

import geoip2
import geoip2.database

    rasn = geoip2.database.Reader('GeoLite2-ASN_20180206/GeoLite2-ASN.mmdb')
    rloc = geoip2.database.Reader('GeoLite2-City_20180206/GeoLite2-City.mmdb')
    print(rloc.city("103.63.30.101"))
    print(rasn.asn("103.63.30.101"))

The asn query fails with an address not found error. Nonetheless, the prefix exists in the equivalent CSV database and I can successfully retrieve the IP from https://www.maxmind.com/en/geoip-demo. 

Am I using the API incorrectly?

**Comment by oschwald** [comment]
That IP address is not in the binary database. If you think this is a mistake, please raise the issue with [support@maxmind.com](mailto:support@maxmind.com).

**Comment by crotsos** [comment]
So does that mean that the CSV and the binary databases are not identical? It is not explicit in the data description.

**Comment by oschwald** [comment]
I have not checked the CSV database. They should be identical for any given month, but it is possible that they are not due to a bug. The issue was closed as this is not a bug in the Python API as the data is not in the database. Support should be able to help you with the data question.
