### ISSUE TITLE
No module named 'geoip2.database'

### ISSUE THREAD

**Issue by papaiatis** [maxmind/GeoIP2-python#54]
I wanted to try out this library, followed the install instructions as follows:

`pip install geoip2`
-> successfully installed

```
python
>>> import geoip2.webservice
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/geoip2.py", line 1, in <module>
    import geoip2.database
ModuleNotFoundError: No module named 'geoip2.database'; 'geoip2' is not a package
```

Using python 3.6.5.
I tried pip3, pip3.6, python, python3, python3.6, but neither combo worked. I can successfully import other modules like urllib3, requests, etc.

```
root@545ec389e230:/usr/local/lib/python3.6/site-packages/geoip2# ls -lahi
total 76K
 48930118 drwxr-sr-x. 3 root staff  170 Jun 14 14:37 .
 41536224 drwxr-sr-x. 1 root staff 4.0K Jun 14 14:37 ..
101268987 -rw-r--r--. 1 root staff  199 Jun 14 14:37 __init__.py
 48930127 drwxr-sr-x. 2 root staff  247 Jun 14 14:37 __pycache__
101268988 -rw-r--r--. 1 root staff  458 Jun 14 14:37 compat.py
101268989 -rw-r--r--. 1 root staff 7.5K Jun 14 14:37 database.py
101268990 -rw-r--r--. 1 root staff 1.2K Jun 14 14:37 errors.py
101268991 -rw-r--r--. 1 root staff  410 Jun 14 14:37 mixins.py
101269462 -rw-r--r--. 1 root staff  14K Jun 14 14:37 models.py
101271072 -rw-r--r--. 1 root staff  18K Jun 14 14:37 records.py
101271073 -rw-r--r--. 1 root staff 9.0K Jun 14 14:37 webservice.py
```

**Comment by oschwald** [comment]
Does `import geoip2` work? Does it work after doing `python -m pip install geoip2`?

**Comment by papaiatis** [comment]
Yes, `import geoip2` does not give me any error.
And yes, it does work if I install the modules this way: `python -m pip install geoip2`.
Why is the difference? Can you explain it to me?

**Comment by papaiatis** [comment]
So it looks like something was wrong with my setup. I'm using Docker to run this python code.
I recreated this docker container and not only your suggestion works but the basic `pip install geoip2` as well. 
So sorry for the noise. Don't know what went wrong for me at the first place.

**Comment by Gaucin** [comment]
> Don't know what went wrong for me at the first place.

Could it be the owner (`root`) of the files:
~~~
101268989 -rw-r--r--. 1 root staff 7.5K Jun 14 14:37 database.py
~~~
