### ISSUE TITLE
generate the IP addresses from the ASN database

### ISSUE THREAD

**Issue by randomgambit** [maxmind/GeoIP2-python#55]
Hello and thanks for this wonderful package.

I know I can use this:
```

with geoip2.database.Reader('/path/to/GeoLite2-ASN.mmdb') as reader:
 response = reader.asn('1.128.0.0')
 response.autonomous_system_organization

```
to get the `autonomous_system_organization` for a given IP. 

Something I was not able to figure out is whether this package can generate all the possible `IP`s for each `autonomous_system_organization` in the `maxmind` ASN database. For instance, can we get the IPs by iterating over the IP networks in `CIDR` format that are in the data? Is there a `method` for that?

Thanks!

**Comment by oschwald** [comment]
Unfortunately, this is not currently possible with this package. There is an [issue for `maxminddb`](https://github.com/maxmind/MaxMind-DB-Reader-python/issues/18) that suggests adding the network information to a lookup, which could be used like this. The Perl reader and the third-party Go reader both have a way to iterate over the database, which also could be used for this.

Right now, the easiest solution would be to just use our CSV databases for this purpose. The ASN one can be downloaded from https://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by randomgambit** [comment]
thanks @oschwald , very useful. I may have found a package that can do that

> from netaddr import IPNetwork
> for ip in IPNetwork('192.0.2.0/23'):
...    print '%s' % ip
...
192.0.2.0
192.0.2.1

but that raises two questions:

1. are the IP addresses generated from the CIDR in a deterministic way?
2. **how does `maxmind` come up with the `ASN` mapping anyway**? I have looked online and I cannot find a single source for this kind of data.

Thanks again for helping! Keep up with the great work

**Comment by oschwald** [comment]
This is done in master. It will be
