### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by acc-to-learn** [maxmind/GeoIP2-python#56]
Hi! 

Would be awesome to have asyncio support 😄 

Cheers!

**Comment by oschwald** [comment]
Are you looking for `asyncio` support for the database reader or the web service client?

**Comment by Damdinov** [comment]
@oschwald for web service client

**Comment by DustinTheGreat** [comment]
In would be willing to rewrite it most of it bc my program is asynchronous and relies on this.
But if I wanted to couldn't I just take the e database reader and make it async pretty easily? I know that  the web client would have to be rewritten to not use requests.

**Comment by oschwald** [comment]
None of the file IO in the database reader is async. I am not sure there is that much to gain by making async unless you are forced to use the pure Python implementation in file mode.

**Comment by DustinTheGreat** [comment]
So If i needed to retrieve geoip info with my async function would recommend just downloading DB and querying it within?

**Comment by oschwald** [comment]
I would recommend using the database with the C extension.
