### ISSUE TITLE
AttributeError: 'Subdivisions' object has no attribute 'names'

### ISSUE THREAD

**Issue by AndyXGWang** [maxmind/GeoIP2-python#57]
Hi 

When i get the name of Subdivisions get the following issue:

> AttributeError: 'Subdivisions' object has no attribute 'names'

method

`ipreader = geoip2.database.Reader('GeoLite2-City.mmdb')
ipdetails = ipreader.city(ips)
ipdetails.subdivisions.names.get('zh-CN','')`

How can i get the name of Subdivisions？

Thanks

**Comment by nchelluri** [comment]
Hi, here is some example code for you:

```
>>> import geoip2.database
>>> reader = geoip2.database.Reader('GeoLite2-City.mmdb')
>>> response = reader.city('128.101.101.101')
>>> response.subdivisions.most_specific.names['zh-CN']
u'\u660e\u5c3c\u82cf\u8fbe\u5dde'
>>> print response.subdivisions.most_specific.names['zh-CN']
明尼苏达州
>>> for subdivision in response.subdivisions:
...   print subdivision.names['zh-CN']
... 
明尼苏达州
>>> 
```
