### ISSUE TITLE
geoip2.database imports maxminddb.MODE_FD which no longer exists

### ISSUE THREAD

**Issue by jeroenh** [maxmind/GeoIP2-python#62]
```
Python 3.6.6 (default, Aug  7 2018, 11:27:19)
[GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)] on freebsd11
Type "help", "copyright", "credits" or "license" for more information.
>>> import geoip2
>>> import geoip2.database
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/geoip2/database.py", line 11, in <module>
    from maxminddb import (MODE_AUTO, MODE_MMAP, MODE_MMAP_EXT, MODE_FILE,
ImportError: cannot import name 'MODE_FD'
>>> import maxminddb
>>> maxminddb.
maxminddb.InvalidDatabaseError(  maxminddb.MODE_MMAP_EXT          maxminddb.errors                 maxminddb.os
maxminddb.MODE_AUTO              maxminddb.Reader(                maxminddb.extension              maxminddb.reader
maxminddb.MODE_FILE              maxminddb.compat                 maxminddb.file
maxminddb.MODE_MEMORY            maxminddb.const                  maxminddb.maxminddb
maxminddb.MODE_MMAP              maxminddb.decoder                maxminddb.open_datab
```

**Comment by oschwald** [comment]
This [does exist](https://github.com/maxmind/MaxMind-DB-Reader-python/blob/master/maxminddb/__init__.py#L11-L12) in `maxminddb` 1.4.0+. You probably need to update that. It does look like we properly depend on 1.4.0+. How did you install `geoip2`?

**Comment by jeroenh** [comment]
On FreeBSD using the ports system. Apparently the maxmind port is outdated:

https://www.freshports.org/net/py-maxminddb/

Apparently, the GeoIP2 port maintainer did not realise that an update was necessary.
https://www.freshports.org/net/py-GeoIP2/

I'll shoot in a bug report there.

**Comment by ocochard** [comment]
Oops, the maintainer is the same person for both net/py-GeoIP2 and net/py-maxminddb, and it's me :-(
Sorry for this breakage: it should be fixed now (FreeBSD ports net/py-maxminddb was just updated to 1.4.1).

**Comment by oschwald** [comment]
@ocochard, thanks! I don't know how the FreeBSD builds work, but is there anything we can do in our packaging of `geoip2` to reduce the likelihood of this happening in the future?
