### ISSUE TITLE
Passing IP to Reader.Country causing AddressNotFoundError exception

### ISSUE THREAD

**Issue by ikwyl6** [maxmind/GeoIP2-python#68]
I am grabbing IPs from my lighttpd log to put them in a `Counter` object so I can for one, count all occurrences of the IP, and two - to pass that IP to the reader.country lookup so I get the location of the address. When I do this, it throws a `AddressNotFoundError` exception. To try and found out the problem, I print the `type` of the value and it tells me it is infact a string. I even use the `strip()` function to see if there are leading and trailing spaces but it still throws this exception. 

If I pass a literal IP to the function which is one of the IPs in this list (ex: '142.93.25.225') the function works fine (See last two lines in the code below). Any ideas?

See below:

```
#!/usr/bin/python
  
# Count all IPs that are hitting webserver 

import re
from collections import Counter
import geoip2.database

logfile = "/var/log/lighttpd/lighttpd.log"

# regex to Grab IPs
myregex = r'(^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})' #.*"(.*)"'
ipcount = Counter()

with open(logfile) as f:
    for line in f:
        my_iplist = re.findall(myregex,line)
        # Add the ip to the Counter obj
        ipcount.update(my_iplist)
    # Loop through the Counter obj and output all the stuff
    reader = geoip2.database.Reader("/home/alarm/geolite2/GeoLite2-Country_20181023/GeoLite2-Country.mmdb")
    for k, v in ipcount.most_common():
        try:
            geo = reader.country(k.strip())
            #geo.insights('128.101.101.101')
            # Forget the IPs that hit webserver once..
            if (v > 1): print("Count: " + str(v) + " IP Address: " + str(k) + " Country: " + geo.country.name + " Loc: " + geo.location + " TZ: " + geo.timezone)
        except:
            #print ("exception..." + k)
            pass
    geo1 = reader.country('142.93.25.225')
    print("Count: " + str(v) + " IP Address: " + geo1.traits.ip_address + " Continent: " + geo1.continent.code + " Country: " + str(geo1.country.name) + " Loc: ")

```

**Comment by oschwald** [comment]
An `AddressNotFoundError` will be raised if the address is not in the database. See [the documentation](https://github.com/maxmind/GeoIP2-python#database-reader-exceptions). In particular, private and most protected addresses will not appear in the database. You should handle this exception appropriately for your use case.

**Comment by ikwyl6** [comment]
But the output of the last two lines in my script when looking up the 142.93.25.255 IP finds the country but when it looks up the exact same IP usng the `for line in f` loop, it does not find the country for that same IP.

**Comment by ikwyl6** [comment]
Hi - could you reopen this bug so it can be looked at more closely?

**Comment by oschwald** [comment]
Could you provide a simple, self-contained test case? As described, it sounds like a bug in the script rather than `geoip2`.

**Comment by ikwyl6** [comment]
Hi - did you run the script with log file?

**Comment by ikwyl6** [comment]
Hi - have you run this script? Can the issue be put into "Open" state.

**Comment by horgh** [comment]
I tried out your code. The exception you're hitting is this:

```
'Country' object has no attribute 'location'
```

The country model does not have that attribute.

If I modify your code to print out only `geo.country.name` then there are no exceptions.

e.g.:

```python
        try:
            geo = reader.country(k.strip())
            #print("Loop, Count: " + str(v) + " IP Address: " + str(k) + " Country: " + geo.country.name + " Loc: " + geo.location + " TZ: " + geo.timezone)
            print("Loop, Count: " + str(v) + " IP Address: " + str(k) + " Country: " + geo.country.name)
        except Exception as err:
            print ("exception... " + k)
            print err
            pass
```
