### ISSUE TITLE
Painfully slow, Stuck.

### ISSUE THREAD

**Issue by quantumcore** [maxmind/GeoIP2-python#78]
Maxmind GeoIP2 Database is painfully slow. Stuck for 15 minutes then it finally gets the information.  Is there a way around this?

**Comment by oschwald** [comment]
If it takes 15 minutes to do a single lookup, it sounds like there is some sort of file-system level issue on your machine. The expected performance is around 2000-4000 lookups per second for the pure Python version and 50,000 to 150,000 lookups per second with the C extension.

**Comment by quantumcore** [comment]
Okay. Turns out it wasn't slow. The problem was in my Code. **Apologies for this issue.**
