### ISSUE TITLE
IPv6 with Scope-ID Support

### ISSUE THREAD

**Issue by dwasyl** [maxmind/GeoIP2-python#81]
When running `GeoIP().city()` on an IPv6 address that includes scope information it fails to validate the address returned a serious of errors from `ipaddress.py`. Rather than return the validation error, it would make more sense if GeoIP dropped the scope id for address determination.

Based on the IPv6 specifications ([https://en.wikipedia.org/wiki/IPv6_address#Scoped_literal_IPv6_addresses](https://en.wikipedia.org/wiki/IPv6_address#Scoped_literal_IPv6_addresses), IPv6 addresses can include scope-id information and still be valid. The scope id is expressed as a `%` and a descriptor at the end of the IPv6 address.

This was tested on Python 3.7 running GeoIP2.

**Comment by oschwald** [comment]
I'd suggest raising this against `ipaddress`. It seems out of scope for this module in particular.

**Comment by dwasyl** [comment]
Fair enough, and now that I'm going through the `Python` PR list, there seem to be a couple of efforts to address this problem there.
