### ISSUE TITLE
IP with country None

### ISSUE THREAD

**Issue by peca11** [maxmind/GeoIP2-python#88]
Hi, 
I found an IP that returns country None. 
This is the IP - "66.249.93.24"

`g = GeoIP2()`
`g.country('66.249.93.24')`
returns {'country_code': None, 'country_name': None}

Im using geoip2==3.0.0

I have checked the IP in other sources, 
https://whatismyipaddress.com/ip/66.249.93.24 - "Country" field is also empty
https://www.iplocation.net/ - Country field returns United States
I'm not  sure what it should return.

It seems that the IP belongs to Google. From what I understand it's used for Google webmail in Europe.

Should I report this issue here? https://support.maxmind.com/geoip-data-correction-request/correct-a-geoip-location/
In the form its mandatory to select a country, but I'm not sure which country it should return.

**Comment by klp2** [comment]
Data issues are typically better dealt with by contacting support@maxmind.com

In this particular case, we only map the IP to the continent level, as it appears that it is not fixed in any one particular country, so the results appear to be as expected.

**Comment by peca11** [comment]
Ok, thanks for the feedback!
