### ISSUE TITLE
Pre-4.0 versions no longer compatible with Python 2

### ISSUE THREAD

**Issue by mrpgraae** [maxmind/GeoIP2-python#92]
After release of version 4.0, earlier versions of geoip2 tries to install minmaxddb 2.0.0, which is not compatible with python 2.
I think you need to pin minmaxddb to `<2.0` in pre-4.0 versions of geoip2.

**Comment by mrpgraae** [comment]
Sorry, the dependency is called maxminddb

**Comment by oschwald** [comment]
This should be fixed with https://github.com/maxmind/MaxMind-DB-Reader-python/pull/70.

**Comment by CrimsonGlory** [comment]
(for those reaching here, the fix is to hardcode ```maxminddb==1.5.4 ``` when installing geoip2 on Python 2.7)
